name: Leaked Secrets Scan
on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
    - name: TruffleHog OSS
      uses: trufflesecurity/trufflehog@main
      with:
        # Repository path
        # path: ./
        # Start scanning from here (usually main branch).
        base: ${{ github.event.repository.default_branch }}
        # Scan commits until here (usually dev branch).
        head: HEAD
        # Extra args to be passed to the trufflehog cli.
        extra_args: --debug
